name: Deploy Infra
on:
  push:
    paths:
      - 'infra/**/*'

jobs:
  deploy:
    name: Update infra
    runs-on: windows-latest
    environment:
      name: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy the infra
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          ./infra/deploy-infra.ps1
